version: '3.8'
services:
  checkmk:
    container_name: checkmk
    hostname: checkmk
    # you can configure the desired version here i. e. 2.2.0p22
    image: checkmk/check-mk-raw:2.2.0-latest
    restart: always
    env_file:
     - ./env/checkmk
    tmpfs:
     - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
     - '/etc/localtime:/etc/localtime:ro'
     - './odm-sites:/omd/sites'
    # only accessable within container env, from outside via. nginx
    expose:
     - '5000'
    ports:
     # 8080 is provided via. nginx
     #- '8080:5000'
     - '8000:8000'

  # support for mail notification
  postfix:
    container_name: postfix
    # important to get name resolution from checkmk to postfix
    hostname: postfix
    image: juanluisbaptiste/postfix:latest
    restart: always
    env_file:
     - ./env/postfix
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
    # only accessable within container env
    expose:
     - '25'

  # provide webinterface via. TLS
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    restart: always
    volumes:
     - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
     - ./nginx/YOURCERT.crt:/etc/nginx/cert/YOURCERT.crt
     - ./nginx/YOURCERT.key:/etc/nginx/cert/YOURCERT.key
     - ./nginx/YOURCERT.chain:/etc/nginx/cert/YOURCERT.chain
    ports:
    # nginx running on 443/tcp and will redirect to 5000/tcp checkmk
     - 8080:443
